set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES arm64)
if(PORT STREQUAL "vcpkg-hello-world-2")
    set(VCPKG_DISABLE_COMPILER_TRACKING 1)
endif()
