set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)

if("header-only-good" IN_LIST FEATURES)
    configure_file("${CMAKE_CURRENT_LIST_DIR}/wrong-pkgconfig.pc.in" "${CURRENT_PACKAGES_DIR}/share/pkgconfig/wrong-pkgconfig.pc" @ONLY)
endif()
if("header-only-bad" IN_LIST FEATURES)
    configure_file("${CMAKE_CURRENT_LIST_DIR}/wrong-pkgconfig.pc.in" "${CURRENT_PACKAGES_DIR}/lib/pkgconfig/wrong-pkgconfig.pc" @ONLY)
endif()
set(LIBS "Libs: \"-L${libdir}\" -lwrong-pkgconfig")
if("lib-good" IN_LIST FEATURES)
    configure_file("${CMAKE_CURRENT_LIST_DIR}/wrong-pkgconfig.pc.in" "${CURRENT_PACKAGES_DIR}/lib/pkgconfig/wrong-pkgconfig.pc" @ONLY)
endif()
if("lib-bad" IN_LIST FEATURES)
    configure_file("${CMAKE_CURRENT_LIST_DIR}/wrong-pkgconfig.pc.in" "${CURRENT_PACKAGES_DIR}/lib/wrong-pkgconfig.pc" @ONLY)
endif()
if("debug-good" IN_LIST FEATURES)
    configure_file("${CMAKE_CURRENT_LIST_DIR}/wrong-pkgconfig.pc.in" "${CURRENT_PACKAGES_DIR}/debug/lib/pkgconfig/wrong-pkgconfig.pc" @ONLY)
endif()
if("debug-bad" IN_LIST FEATURES)
    configure_file("${CMAKE_CURRENT_LIST_DIR}/wrong-pkgconfig.pc.in" "${CURRENT_PACKAGES_DIR}/debug/lib/wrong-pkgconfig.pc" @ONLY)
endif()

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/../../../../LICENSE.txt" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}/" RENAME copyright)
