
if(NOT VCPKG_POST_INCLUDE_CHECK_TEST1)
    message(FATAL_ERROR "VCPKG_POST_INCLUDE_CHECK_TEST1 failed")
endif()

if(NOT VCPKG_POST_INCLUDE_CHECK_TEST2)
    message(FATAL_ERROR "VCPKG_POST_INCLUDE_CHECK_TEST2 failed")
endif()

message(STATUS "VCPKG_POST_INCLUDE_CHECK_TEST succesful")