name: PR Build

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  builds:
    uses: ./.github/workflows/build.yaml
    with:
      format: true
